from myapp.models.Asset import Asset
from myapp.models.Country import Country
from myapp.models.Dept import Dept
from myapp.models.List import List
from myapp.models.Reason import Reason
from myapp.models.Staff import Staff
from myapp.models.Stock import Stock
from myapp.models.Supplier import Supplier
from myapp.models.ModulePermission import ModulePermission
from myapp.models.UserProfile import UserProfile